networks:
  backend-network: {}
  clickhouse-network: {}
  frontend-network: {}
  mongo-network: {}
  mtf-network: {}
  rabbitmq-network: {}
  recognition-network: {}
services:
  clickhouse:
    hostname: clickhouse-server
    image: yandex/clickhouse-server:19.13.5.44
    networks:
      clickhouse-network: null
    ports:
    - 8123:8123/tcp
  mongo:
    image: mongo:4.2.0
    networks:
      mongo-network: null
    ports:
    - 27017:27017/tcp
    volumes:
    - /var/lib/recognition/mongo:/data/db:rw
  nginx:
    depends_on:
      recognition-webapi:
        condition: service_started
    image: nginx:1.15.6-alpine
    networks:
      frontend-network: null
    ports:
    - 80:80/tcp
    restart: always
    volumes:
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:rw
    - ./nginx/locations/recognition.conf:/etc/nginx/conf.d/locations/recognition.conf:rw
    - ./nginx/upstreams/recognition.conf:/etc/nginx/conf.d/upstreams/recognition.conf:rw
  rabbitmq:
    image: rabbitmq:3.7.8-management
    networks:
      rabbitmq-network: null
    ports:
    - 5672:5672/tcp
    - 15672:15672/tcp
  recognition-detector:
    depends_on:
      clickhouse:
        condition: service_started
      mongo:
        condition: service_started
      rabbitmq:
        condition: service_started
    environment:
      LOGGER_JSON_INDENT: '4'
      PERSONFINDER_MONGO_URI: mongodb://mongo:27017
      PYTHONPATH: /caffe/python
      RECOGNITION_DECODER_MAX_QUEUE_SIZE: '5'
      RECOGNITION_DECODER_MAX_QUEUE_SIZE_RAW_ARRAY: '40'
      RECOGNITION_DETECTOR_BATCH_SIZE: '20'
      RECOGNITION_DETECTOR_THRESHOLD: '0.45'
      RECOGNITION_IMAGE_STORAGE_HOST: clickhouse
      RECOGNITION_MONGO_HOST: mongodb://mongo:27017
      RECOGNITION_PLAYLIST_OFFSET: '10'
      RECOGNITION_PM_MONGO_HOST: mongodb://mongo:27017
      RECOGNITION_RABBITMQ_HOST: rabbitmq
      RECOGNITION_RABBITMQ_PREFETCH_COUNT: '20'
      RECOGNITION_STREAM_RETRY_TIMEOUT: '5'
    image: faceterteam/recognition.detector.worker:v1.0.19
    mem_limit: 4gb
    memswap_limit: 2gb
    networks:
      backend-network: null
      clickhouse-network: null
      mongo-network: null
      rabbitmq-network: null
      recognition-network: null
    oom_kill_disable: true
    ports:
    - 9989:22/tcp
    runtime: nvidia
    volumes:
    - /docker-data/recognition/detector/logs:/app/logs:rw
  recognition-feature-extractor:
    depends_on:
      clickhouse:
        condition: service_started
      rabbitmq:
        condition: service_started
    environment:
      PYTHONPATH: /caffe/python
      RECOGNITION_FEATURE_EXTRACTOR_BATCH_SIZE: '3'
      RECOGNITION_FE_RPC_ROUTING_KEY: FeatureExtractor.Task
      RECOGNITION_IMAGE_STORAGE_HOST: clickhouse
      RECOGNITION_RABBITMQ_HOST: rabbitmq
      RECOGNITION_RABBITMQ_PREFETCH_COUNT: '1'
    image: faceterteam/recognition.featureextractor.worker:v1.0.4
    networks:
      backend-network: null
      clickhouse-network: null
      rabbitmq-network: null
      recognition-network: null
    ports:
    - 9999:9999/tcp
    runtime: nvidia
  recognition-mtf-webapi:
    environment:
      PYTHONPATH: /caffe/python
      RECOGNITION_MTF_BATCH_SIZE: '1'
    image: faceterteam/mtf.webapi:v1.0.8
    mem_limit: 6g
    mem_swappiness: 80
    memswap_limit: 8g
    networks:
      backend-network: null
    ports:
    - 1743:1743/tcp
    restart: always
    runtime: nvidia
  recognition-person-storage:
    depends_on:
      mongo:
        condition: service_started
      rabbitmq:
        condition: service_started
    environment:
      PERSONFINDER_MONGO_URI: mongodb://mongo:27017
      RECOGNITION_CACHE_SIZE: '50'
      RECOGNITION_DISTANCE_THRESHOLD: '0.45'
      RECOGNITION_ERROR_ROUTING_KEY: PersonStorageError
      RECOGNITION_INPUT_ROUTING_KEY: MutationVectorEvent
      RECOGNITION_MONGO_HOST: mongodb://mongo:27017
      RECOGNITION_OUTPUT_ROUTING_KEY: NewVectorEvent
      RECOGNITION_PM_MONGO_HOST: mongodb://mongo:27017
      RECOGNITION_RABBITMQ_HOST: rabbitmq
    image: faceterteam/recognition.personstorage:v1.0.10
    networks:
      backend-network: null
      mongo-network: null
      rabbitmq-network: null
      recognition-network: null
  recognition-personfinder-webapi:
    depends_on:
      mongo:
        condition: service_started
    environment:
      PERSONFINDER_DETECTOR_THRESHOLD: '0.9'
      PERSONFINDER_FEATURE_EXTRACTOR_URI: http://recognition-feature-extractor:9999
      PERSONFINDER_MONGO_URI: mongodb://mongo:27017
      RECOGNITION_MONGO_HOST: mongodb://mongo:27017
      RECOGNITION_PM_MONGO_HOST: mongodb://mongo:27017
    image: faceterteam/recognition.personfinder:v1.0.3
    networks:
      backend-network: null
      mongo-network: null
      recognition-network: null
    ports:
    - 9123:8080/tcp
  recognition-project-manager-worker:
    depends_on:
      mongo:
        condition: service_started
      rabbitmq:
        condition: service_started
      recognition-scorer:
        condition: service_started
    environment:
      ConnectionStrings:MongoDb: mongodb://mongo:27017/recognition_public_api
      ENABLE_LOGGING: "true"
      ENVIRONMENT: Production
      RabbitMq__host: rabbitmq
      RabbitMq__uri: amqp://rabbitmq/
    image: faceterteam/recognition.projectmanager.worker:v1.0.8
    networks:
      backend-network: null
      mongo-network: null
      rabbitmq-network: null
      recognition-network: null
  recognition-scorer:
    container_name: recognition-scorer
    depends_on:
      clickhouse:
        condition: service_started
      rabbitmq:
        condition: service_started
    environment:
      PYTHONPATH: /caffe/python
      RECOGNITION_IMAGE_STORAGE_HOST: clickhouse
      RECOGNITION_IMAGE_TABLE_TTL: '3'
      RECOGNITION_RABBITMQ_HOST: rabbitmq
      RECOGNITION_RABBITMQ_PREFETCH_COUNT: '1'
      RECOGNITION_SCORER_BATCH_REDUCE_MIN_SIZE: '2'
    image: faceterteam/recognition.scorer.worker:v1.0.16
    networks:
      backend-network: null
      clickhouse-network: null
      rabbitmq-network: null
      recognition-network: null
    runtime: nvidia
    volumes:
    - /docker-data/recognition/scorer/logs:/app/logs:rw
  recognition-tracklet:
    depends_on:
      clickhouse:
        condition: service_started
      mongo:
        condition: service_started
      rabbitmq:
        condition: service_started
    environment:
      PERSONFINDER_MONGO_URI: mongodb://mongo:27017
      RECOGNITION_CALLBACK_REQUEST_TIMEOUT: '5'
      RECOGNITION_FEATURE_EXTRACTOR_HOST: http://recognition-feature-extractor:9999
      RECOGNITION_MONGO_HOST: mongodb://mongo:27017
      RECOGNITION_PM_DISTANCE_THRESHOLD: '0.45'
      RECOGNITION_PM_DROP_TABLES_EXPIRE_PERIOD: '15200'
      RECOGNITION_PM_IMAGE_STORAGE_HOST: clickhouse
      RECOGNITION_PM_MONGO_HOST: mongodb://mongo:27017
      RECOGNITION_PM_PROBABLY_DISTANCE_THRESHOLD: '0.6'
      RECOGNITION_PM_SCORE_LOWER_THRESHOLD: '0.005'
      RECOGNITION_PM_SCORE_THRESHOLD: '0.7'
      RECOGNITION_RABBITMQ_HOST: rabbitmq
      RECOGNITION_RABBITMQ_PREFETCH_COUNT: '1'
      RECOGNITION_TRACKLET_INPUT_ROUTING_KEY: ScoredBatchEvent
    image: faceterteam/recognition.tracklet.worker:v1.0.41
    networks:
      backend-network: null
      clickhouse-network: null
      mongo-network: null
      rabbitmq-network: null
      recognition-network: null
    volumes:
    - /tmp/Resources:/app/Resources:rw
  recognition-webapi:
    depends_on:
      mongo:
        condition: service_started
      rabbitmq:
        condition: service_started
    environment:
      ConnectionStrings:MongoDb: mongodb://mongo:27017/recognition_public_api
      ENABLE_LOGGING: "true"
      ENVIRONMENT: Production
      RabbitMq__host: rabbitmq
      RabbitMq__uri: amqp://rabbitmq/
    image: faceterteam/recognition.public.webapi:v1.0.11
    networks:
      backend-network: null
      frontend-network: null
      mongo-network: null
      rabbitmq-network: null
      recognition-network: null
    ports:
    - 8585:80/tcp
version: '2.4'

