version: '2.4'

services:
  nginx:
    image: nginx:1.15.6-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frontend-network
    restart: always